const CATEGORY_DATA = 'CATEGORY_DATA' // 总分类数据
const CATEGORY_DETAIL_DATA = 'CATEGORY_DETAIL_DATA' // 分类具体细节数据
const FICTION_DATA = 'FICTION_DATA' // 获取某分类小说
const LOAD_MORE_FICTION_DATA = 'LOAD_MORE_FICTION_DATA' // 加载更多小说

export {
    CATEGORY_DATA,
    CATEGORY_DETAIL_DATA,
    FICTION_DATA,
    LOAD_MORE_FICTION_DATA
}